ViacomInc/data-point

lib/entity-types/entity-hash/reducer.js, lib/entity-types/entity-hash/reducer.test.js, lib/utils/index.js, lib/utils/utils.test.js
logs value, type and documentation url for reference
#3
=> fix(entity-hash): fixes unclear error message

README.md
Removed extra ) on the Data-point example with ExpressJS
14
=> docs($readme): Fixed express example on readme file

README.md
Added youtube hello world example tutorial link to the getting started section
8
=> docs($docs): Add video link to readme

README.md
=> docs(README.md): reformat examples to be more readable on mobile devices

README.md
fixed a couple of typos, added a clarification about `acc.params`, and fixed some collection examples
=> docs(README.md): fix typos and examples after a read through

README.md, lib/entity-types/entity-request/reducer.js, lib/entity-types/entity-request/reducer.test.js, lib/utils/index.js, lib/utils/utils.test.js
=> feat(entity-request): ability to inspect a request before making the call

lib/entity-types/entity-request/reducer.js, lib/entity-types/entity-request/reducer.test.js
=> fix(request-entity): request inspect options not showing

lib/core/factory.js
=> fix(core/factory): fix datapoint factory fails if no entities are passed

packages/data-point/lib/reducer-entity/factory.js, packages/data-point/lib/reducer-function/factory.js, packages/data-point/lib/reducer/__snapshots__/factory.test.js.snap, packages/data-point/lib/reducer/factory.js, packages/data-point/lib/reducer/factory.test.js, packages/data-point/lib/stores/__snapshots__/store-manager.test.js.snap, packages/data-point/lib/stores/store-manager.js, packages/data-point/lib/stores/store-manager.test.js, packages/data-point/lib/transform-expression/__snapshots__/factory.test.js.snap, packages/data-point/lib/transform-expression/factory.js, packages/data-point/lib/transform-expression/factory.test.js
=> feat(parsing): improves errors parse messages

packages/data-point/lib/core/transform.js, packages/data-point/lib/core/transform.test.js
=> Do not pass original acc.value into _.defaults

packages/data-point/README.md
This fixes some broken readme examples (I didn't test all of the examples though, so this doesn't guarantee they all work). Some of them didn't run because of JS syntax errors, and many of the `request` entities that target github were not working because they needed headers.
=> Fix examples in the readme

packages/data-point/README.md, packages/data-point/lib/entity-types/entity-collection/reducer.js, packages/data-point/lib/entity-types/entity-hash/reducer.js, packages/data-point/lib/entity-types/parse-compose/parse-compose.js, packages/data-point/lib/entity-types/parse-compose/parse-compose.test.js
=> style: Replace the name ComposeModifier with ComposeReducer

packages/data-point/lib/entity-types/entity-collection/factory.js, packages/data-point/lib/entity-types/entity-collection/factory.test.js, packages/data-point/lib/entity-types/entity-collection/reducer.js
=> fix(entity-collection): Fix execution order of collection entity modifiers

.travis.yml, package.json
=> ci(travis): switch to yarn usage

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
**What**: Adds the templates for GitHub Issues and PRs
**Why**: This closes #64 and makes it easier for people to contribute to the project 😄 
**How**: Copied from another project tbh. 🙊 
**Checklist**:
This uses the template!
=> docs(.github): Add templates for GitHub issues and PRs

README.md, packages/data-point-cache/README.md, packages/data-point-express/README.md, packages/data-point-service/README.md, packages/data-point/README.md
**What**: fix badges in README files
**Why**: #68
**How**: update branch it points to
**Checklist**:
- [N/A] Tests
=> docs(**/README.md): points badges to master branch

packages/data-point/lib/entity-types/entity-collection/factory.js, packages/data-point/lib/entity-types/entity-control/factory.js, packages/data-point/lib/entity-types/entity-entry/factory.js, packages/data-point/lib/entity-types/entity-hash/factory.js, packages/data-point/lib/entity-types/entity-request/factory.js, packages/data-point/lib/entity-types/entity-transform/factory.js
**What**: Use consistent naming for entity functions
**Why**: #71 
**How**: Renaming functions
**Checklist**:
=> style(entity-types): Use consistent naming for entity functions

CHANGELOG.md, lerna.json, packages/data-point-cache/CHANGELOG.md, packages/data-point-cache/package.json, packages/data-point-express/CHANGELOG.md, packages/data-point-express/package.json, packages/data-point-service/CHANGELOG.md, packages/data-point-service/package.json, packages/data-point/CHANGELOG.md, packages/data-point/package.json
**What**:
adds lerna registry
**Why**:
to get around https://github.com/lerna/lerna/issues/896
**How**:
adds registry field to lerna.json
**Checklist**:
=> Add lerna registry

packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/middleware/resolve.js, packages/data-point/lib/reducer-entity/resolve.js, packages/data-point/lib/reducer-object/resolve.js, packages/data-point/lib/transform-expression/resolve.js, packages/data-point/lib/transform-expression/resolve.test.js
**What**: Rename `store` parameters to `manager`
**Why**: To make it more clear that the parameter is the object created here:
https://github.com/ViacomInc/data-point/blob/master/packages/data-point/lib/core/factory.js#L51
**Checklist**:
=> Rename store parameter to manager

packages/data-point/README.md
**What**: This is mostly a stylistic change to the README for `data-point`. There was one section for "Chained Reducers" that was removed entirely because it was duplicative of the TransformExpression section.
**Why**: This makes the README a bit easier to parse by making the examples collapsible.
**How**: Typing
**Checklist**:
This closes #78 and closes #98
=> Readme updates

packages/data-point/README.md, packages/data-point/examples/reducer-conditional-operator.js, packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/entity-types/base-entity/resolve.test.js, packages/data-point/lib/reducer-entity/factory.js, packages/data-point/lib/reducer-entity/factory.test.js, packages/data-point/lib/reducer-object/__snapshots__/factory.test.js.snap, packages/data-point/lib/utils/index.js, packages/data-point/lib/utils/utils.test.js
**What**: adds conditional operator #46
**Why**: allows entities to be conditionally executed
**Checklist**:
- [N/A] Added username to **all-contributors** list
=> feat(data-point/entities): adds conditional reducer operator

.github/ISSUE_TEMPLATE.md
**What**: Make the headers bold in the issue template
**Why**: Bold headers look nice.
**Checklist**:
=> Make headers bold in issue template markdown

packages/data-point/lib/entity-types/entity-request/__snapshots__/resolve.test.js.snap, packages/data-point/lib/entity-types/entity-request/resolve.js, packages/data-point/lib/entity-types/entity-request/resolve.test.js, packages/data-point/lib/utils/__snapshots__/utils.test.js.snap, packages/data-point/lib/utils/index.js, packages/data-point/lib/utils/utils.test.js
**What**: #110 
**Why**:  #110
**How**: logs request critical info and attaches it to error.message
**Checklist**:
- [N/A] Documentation
- [N/A] Added username to **all-contributors** list
=> feat(data-point/request-entity): improves request error message

.github/ISSUE_TEMPLATE.md, packages/data-point-cache/lib/in-memory.js, packages/data-point-cache/lib/in-memory.test.js
**What**: refactor code to make test reliable
**Why**: test were randomly failing due to how it relied on `setInterval`
**How**: isolating swipe logic so it can be unit tested independently of its implementation 
**Checklist**:
- [N/A ] Documentation
=> fix(data-point-cache/in-memory): refactor code to make tests reliable

packages/data-point/README.md, packages/data-point/lib/entity-types/entity-collection/__snapshots__/resolve.test.js.snap, packages/data-point/lib/entity-types/entity-collection/resolve.js, packages/data-point/lib/entity-types/entity-collection/resolve.test.js, packages/data-point/lib/entity-types/entity-hash/__snapshots__/resolve.test.js.snap, packages/data-point/lib/entity-types/entity-hash/resolve.js, packages/data-point/lib/entity-types/entity-hash/resolve.test.js, packages/data-point/lib/entity-types/integrations.test.js
**What**:  #45
**Why**: to remove unexpected behaviours when entites where being resolved if value was not right type
**How**:s
remove premature check and delegate to entity validation after value is resolved
**Checklist**:
=> Entities skip if empty should error

packages/data-point/lib/entity-types/base-entity/factory.js, packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/entity-types/base-entity/resolve.test.js, packages/data-point/lib/reducer-types/reducer-function/resolve.js, packages/data-point/lib/reducer-types/reducer-list/resolve.js
**What**: Add `manager` parameter to `resolveErrorReducers` function as a first step towards #126; also adds jsdoc to some functions
**Why**: #126 
**Checklist**:
=> Use _.partial less with resolveReducer

packages/data-point/README.md
**What**: group patterns and best practices
**Why**: #109
**How**: moving them down to their own section
**Checklist**:
=> docs(data-point/README): group patterns and best practices

packages/data-point/lib/reducer-types/reducer-helpers/reducer-assign/factory.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-assign/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-filter/factory.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-filter/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-find/factory.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-find/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-map/factory.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-map/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-omit/factory.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-omit/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-pick/factory.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-pick/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-stub.test.js
**What**: Remove unnecessary `'use strict'` from top of files
**Why**: #131
**How**: The magic of `ctrl-f`
**Checklist**:
- [N/A] Documentation
- [N/A] Tests
=> refactor(reducer-helpers/*): Remove unnecessary 'use strict'

packages/data-point/README.md, packages/data-point/examples/async-example.js, packages/data-point/examples/async-example.mocks.js, packages/data-point/examples/entity-hash-addKeys.js, packages/data-point/examples/entity-hash-mapKeys.js, packages/data-point/examples/entity-hash-omitKeys.js, packages/data-point/examples/entity-hash-pickKeys.js, packages/data-point/examples/entity-request-basic.js, packages/data-point/examples/entity-request-basic.mock.js, packages/data-point/examples/entity-request-before-request.js, packages/data-point/examples/entity-request-options-locals.js, packages/data-point/examples/entity-request-string-template.js, packages/data-point/examples/entity-request-transform-object.js, packages/data-point/examples/entity-request-transform-object.mock.js, packages/data-point/examples/extend-entity-keys.js, packages/data-point/examples/reducer-conditional-operator.js, packages/data-point/examples/reducer-conditional-operator.mock.js
improves examples by simplifying them and using mocks(nock) for requests
**What**: improve examples 
**Why**: some were too complex and missed the point, others were actually making calls to remote services without mocks, this could potentially cause issues on CI by getting banned from those services
**How**: simplified examples, mocked services
**Checklist**:
=> refactor(data-point/examples): refactor examples

packages/data-point/README.md, packages/data-point/lib/core/core.test.js, packages/data-point/lib/core/factory.js
**What**:   #56
**Why**: naming of method was misleading
**How**: adding a singular method, and fixing the plural one
**Checklist**:
**BREAKING CHANGE**: addEntityType is for single, addEntityTypes is for multiple
closes
=> fix(data-point/core): fix addEntityTypes api not consistent

packages/data-point/examples/custom-entity-type.js, packages/data-point/lib/__snapshots__/index.test.js.snap, packages/data-point/lib/index.js, packages/data-point/lib/index.test.js
**What**: #80
**Why**: closes #80
**How**: explicitly exposing methods
**Checklist**:
=>  feat(data-point): explicitly expose set of methods to main API

packages/data-point/lib/reducer-types/reducer-function/factory.js, packages/data-point/lib/reducer-types/reducer-function/resolve.js
**What**: Closes #152
**Why**: Moves some runtime logic to a factory function
**How**: Using `Promise.promisify`
**Checklist**:
=> refactor(data-point/reducer-function): Promisify node style reducer functions

packages/data-point/lib/entity-types/base-entity/resolve.js
**What**: Use `resolveMiddleware` function for `<entity-type>:after` middleware
**Why**: Adds more consistency and closes #156
**Checklist**:
=> refactor(data-point/base-entity): Use resolveMiddleware for every level of middleware

packages/data-point-cache/lib/cache.js, packages/data-point-cache/lib/in-memory.js, packages/data-point-cache/lib/index.js, packages/data-point-cache/lib/redis-client.js, packages/data-point/lib/entity-types/spec/factory.js
**What**: Prettified files in project that were not prettified
**Why**: To maintain a consistent style across all *.js files
**How**:
**Checklist**:
=> style(*.js) formatted *.js files that did not use the prettify standard

.travis.yml, README.md, packages/bench-trial/README.md, packages/data-point-cache/README.md, packages/data-point-codemods/README.md, packages/data-point-express/README.md, packages/data-point-service/README.md, packages/data-point/README.md
**What**: setup codecov
**Why**: coveralls is hanging, has happened more than twice
**How**: changed travis
**Checklist**:
=> ci(travis): setup codecov

packages/data-point/README.md, packages/data-point/lib/__snapshots__/index.test.js.snap, packages/data-point/lib/core/core.js, packages/data-point/lib/entity-types/__snapshots__/factory.test.js.snap, packages/data-point/lib/entity-types/factory.js, packages/data-point/lib/entity-types/factory.test.js, packages/data-point/lib/entity-types/index.js, packages/data-point/lib/helpers/__snapshots__/helpers.test.js.snap, packages/data-point/lib/helpers/helpers.js, packages/data-point/lib/index.js
**What**: Add entity factory functions
**Why**: Gives an easy method for importing/exporting individual entity definitions
**How**: Adds a `createEntityFactory` function and exports a factory for each entity type on the `DataPoint.entityFactories` object
**Checklist**:
=> feat(data-point): Add entity factories

packages/data-point/README.md
**What**: Updates the readme by adding a new section for `Accumulator Object` and combining the `Collection Mapping` section with the `EntityReducer` section
**Why**: Now the index for the `Reducers` section only has links to descriptions for reducer types
**Checklist**:
=> docs(data-point/README.md): Miscellaneous readme updates

packages/data-point/test/utils/reducers.js
**What**: Addresses and removes 2 todo comments
**Why**: closes #187
**How**: Replace `_.set` with `utils.set` to avoid object mutation
**Checklist**:
=> feat: Address todo comments regarding object mutation

packages/data-point-service/lib/factory.js
**What**: Fixed two small typos in factory.js output messages.
**Why**: To improve the overall quality of the project
**How**: Fixing the 2 typos
**Checklist**:
=> fix(factory.js): Fixed two small typos in factory.js output messages.

packages/bench-trial/package.json
**What**: Add `bluebird` dependency to `bench-trial`
**Why**: closes #250
**How**: `yarn add`
**Checklist**:
=> build(bench-trial): Add bluebird dependency to bench-trial

packages/data-point/README.md, packages/data-point/lib/__snapshots__/index.test.js.snap, packages/data-point/lib/helpers/__snapshots__/type-check-functions.test.js.snap, packages/data-point/lib/helpers/index.js, packages/data-point/lib/helpers/type-check-functions.js, packages/data-point/lib/helpers/type-check-functions.test.js, packages/data-point/lib/helpers/type-check-helpers.js, packages/data-point/lib/helpers/type-check-helpers.test.js, packages/data-point/lib/index.js
**What**: Adds a `createTypeCheckReducer` higher order function
**Why**: closes #247
**Checklist**:
=> feat(data-point): Add createTypeCheckReducer to public API

.travis.yml
**What**: update travis file
**Why**: travis is failing to do yarn install
**How**: update travis file
**Checklist**:
=> ci(travis): change install to before_install

packages/data-point/lib/core/core.js, packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/stores/entities.js, packages/data-point/lib/stores/middleware.js, packages/data-point/lib/stores/object-store-manager.js, packages/data-point/lib/stores/store-manager.js
**What**: Replace _.partial with Array.bind
**Why**: closes #259
I ran a very simple test in `bench-trial`:
```js
const DataPoint = require('data-point')
const test = done => {
const dp = DataPoint.create()
dp.resolve('$a', { a: 1 }).asCallback(done)
}
module.exports = [
{
async: true,
name: 'test',
test: test,
benchmark: test
}
]
```
This is the result from `master`:
```
Total number of operations per second: 9,689Hz
```
and this is with my changes:
```
Total number of operations per second: 19,544Hz
```
**Checklist**:
=> feat(data-point): Replace _.partial with Array.bind

lerna.json, package.json
**What**:
Fixed configuration for independent publishing
**Why**:
Had configured lerna wrong to be able to publish independently
**How**:
removes the flag from the publish script, changes **lerna.json** version to `independent`
**Checklist**:
=> fix(lerna): fixes how lerna was configured for publishing

packages/data-point/lib/entity-types/base-entity/__snapshots__/resolve.test.js.snap, packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/entity-types/base-entity/resolve.test.js
=> fix(data-point): fix entity id display on traces

packages/data-point-service/README.md, packages/data-point-service/examples/express-cache-stale-while-revalidate.js, packages/data-point-service/examples/express-simple-cache.js, packages/data-point-service/lib/cache-middleware.js, packages/data-point-service/lib/cache-middleware.test.js
**What**:
re: #276
params.[ttl,cacheKey,staleWhileRevalidate] are now consolidated through params.cache, backward
compatibility is provided with a deprecation warning
**Checklist**:
=> feat(data-point-service): consolidate params.cache

packages/data-point/README.md, packages/data-point/lib/accumulator/factory.js, packages/data-point/lib/entity-types/base-entity/__snapshots__/resolve.test.js.snap, packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/entity-types/integrations.test.js, packages/data-point/package.json
**What**:
traces base entity and exposes scoped debug at accumulator object
**Why**:
closes #285
**Checklist**:
=> feat(data-point): implement debug module

package.json
**What**:
adds an npm script for publishing a to **next** npm tag
**Why**:
so we can do a prerelease of things and test without affecting the latest release
**Checklist**:
=> build(root): script to publish next tag

packages/data-point/README.md, packages/data-point/examples/entity-request-options-override.js, packages/data-point/lib/accumulator/factory.js, packages/data-point/lib/core/transform.js, packages/data-point/lib/entity-types/base-entity/resolve.js, packages/data-point/lib/entity-types/base-entity/resolve.test.js
re #281
**What**: Added support for entity overrides
**Why**: In order to allow global override values 
**How**: Added an override mapping to params
**Checklist**:
=> feat(data-point): Allow entityOverride in options object

packages/data-point/examples/entity-request-options-override.js
**What**: entityOverride example is broken, this fixes the issue
**Why**: because its broken :)
**How**: by fixing it 
**Checklist**:
=> fix(data-point): fixes entityOverride example

packages/data-point/lib/entity-types/base-entity/factory.js, packages/data-point/lib/entity-types/base-entity/factory.test.js
**What**: No longer freezing entity instances.
**Why**: fix #299 
**How**: removes deepFreeze from base-entity#factory
**Checklist**:
=> feat(base-entity): Do not freeze entity instances

packages/data-point-service/lib/__snapshots__/cache-middleware.test.js.snap, packages/data-point-service/lib/cache-middleware.js, packages/data-point-service/lib/cache-middleware.test.js, packages/data-point-service/lib/entity-cache-params.js, packages/data-point-service/lib/entity-cache-params.test.js, packages/data-point-service/lib/redis-controller.js, packages/data-point-service/lib/redis-controller.test.js
**What**: prepare codebase for new revalidation feature
**Why**: too much happening on cache-middleware.js to add a new feature, this PR refactors it so code can be more easily reasoned about
**How**: making code bit more modular
**Checklist**:
=> refactor(data-point-service): refactors modules to prepare for new revalidation feature

packages/data-point/README.md
**What**:
Typos
**Why**:
**How**:
**Checklist**:
=> fix couple of typos

packages/data-point-cache/package.json, packages/data-point-codemods/package.json, packages/data-point-express/package.json, packages/data-point-service/package.json, packages/data-point/package.json, yarn.lock
yarn also added integrity hashes
closes #306
**What**:
fixes suggested vulnerabilities
**Why**:
for security
**How**:
upgrading lodash to latest + adding yarn's integrity hashes
**Checklist**:
=> build(*): upgrade lodash to specific version

.travis.yml, packages/bench-trial/package.json, packages/data-point-cache/README.md, packages/data-point-cache/package.json, packages/data-point-codemods/package.json, packages/data-point-express/README.md, packages/data-point-express/package.json, packages/data-point-service/README.md, packages/data-point-service/package.json, packages/data-point/README.md, packages/data-point/lib/utils/__snapshots__/utils.test.js.snap, packages/data-point/lib/utils/index.js, packages/data-point/package.json
**What**:
adds test for node 10
**Why**:
closes #315
**How**:
upgrades travis for testing for node 8 and 10 
updates documentations and package.json engine settings to 8=>
**Checklist**:
=> ci(*): deprecate node 6 support

packages/data-point/README.md, packages/data-point/lib/entity-types/entity-request/resolve.js, packages/data-point/lib/entity-types/entity-request/resolve.test.js, packages/data-point/lib/entity-types/integrations.test.js, packages/data-point/lib/reducer-types/reducer-list/resolve.test.js, packages/data-point/test/definitions/requests.js
**What**:
will now use acc.value if request.url is empty and acc.value is a non-empty string
**Why**:
#313
**How**:
by adding logic to check if request.url is empty and acc.value is a non-empty string, then use acc.value
**Checklist**:
=> feat(data-point): new logic to resolve Request.url

packages/data-point/README.md, packages/data-point/examples/entity-model-basic.js, packages/data-point/examples/entity-request-options.js, packages/data-point/examples/full-example-instances.js, packages/data-point/examples/reducer-entity-instance.js, packages/data-point/examples/reducer-helper-assign.js, packages/data-point/examples/reducer-helper-filter.js, packages/data-point/examples/reducer-helper-find.js, packages/data-point/examples/reducer-helper-map.js, packages/data-point/examples/registered-entities.js, packages/data-point/examples/trace.js, packages/data-point/lib/__snapshots__/index.test.js.snap, packages/data-point/lib/index.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-constant/resolve.test.js, packages/data-point/lib/reducer-types/reducer-helpers/reducer-parallel/resolve.test.js, packages/data-point/lib/reducer-types/reducer-object/factory.test.js, packages/data-point/lib/reducer-types/reducer-object/resolve.test.js, packages/data-point/test/definitions/requests.js
**What**:
exposes helpers and entity factories via DataPoint
**Why**:
closes #314
**How**:
exposes helpers and entity factories via DataPoint
adds deprecation warnings for DataPoint.helpers and DataPoint.entities
**Checklist**:
=> feat(data-point): exposes helpers and entity factories via DataPoint

package.json, packages/data-point-cache/lib/__mocks__/io-redis.js, packages/data-point-cache/lib/cache.test.js, packages/data-point-cache/lib/io-redis.js, packages/data-point-cache/lib/redis-client.js, packages/data-point-cache/lib/redis-client.test.js, packages/data-point-express/lib/factory.test.js, packages/data-point-express/lib/inspector-middleware.test.js, packages/data-point-express/lib/middleware.test.js, packages/data-point-express/lib/route-middleware.test.js, packages/data-point-express/lib/router-middleware.test.js, packages/data-point-service/lib/__snapshots__/stale-while-revalidate.test.js.snap, packages/data-point-service/lib/entity-cache-params.js, packages/data-point/package.json, yarn.lock
**What**: Updating the `jest` dependency from v21 to v23
**Why**: Newer is better?
=> build(Update from jest 21 to jest 23):

packages/data-point/lib/reducer-types/reducer-path/resolve.js
**What**:
Uses bluebird on resolve function
**Why**:
Promise chain was being affected
closes #332
**How**:
using bluebird instead of the native promise
**Checklist**:
=> feat(data-point): use bluebird internally

yarn.lock
**What**:
update yarn.locl
**Why**:
closes #334
**How**:
by running yarn install, and pushing the changes made to yarn.lock
**Checklist**:
=> build(*): update yarn.lock

packages/data-point/lib/entity-types/entity-request/__snapshots__/resolve.test.js.snap, packages/data-point/lib/entity-types/validate-modifiers/__snapshots__/validate-modifiers.test.js.snap, packages/data-point/lib/entity-types/validate-modifiers/validate-modifiers.js, packages/data-point/lib/utils/__snapshots__/utils.test.js.snap, packages/data-point/lib/utils/index.js, packages/data-point/lib/utils/utils.test.js
**What**:
this change is to remove inconsistencies across node versions
**Why**:
see #346
Unblocks issue #344 and its PR #345 
**How**:
using  json-stringify-safe as a drop-in replacement
**Checklist**:
=> fix(data-point): replace util.inspect with json-stringify-safe

.all-contributorsrc, .travis.yml
**What**:
Adds version check for Node 12 to travis.yml
**Why**:
Issue #344 https://github.com/ViacomInc/data-point/issues/344
**How**:
Adds 12 to travis.yml
**Checklist**:
- [x ] Documentation
- [x ] Ready to be merged 
- [x ] Added username to **all-contributors** list
Test failed * "Hash entity type checking > should throw error from default outputType reducer when output is not valid."
=> Fixes issue #344 & self to all contributors list

package.json, packages/bench-trial/runner.js, packages/data-point-cache/lib/in-memory.js, packages/data-point-cache/lib/in-memory.test.js, packages/data-point-codemods/transforms/hash-and-collection-execution-order.js, packages/data-point-codemods/transforms/reducer-args-acc-to-val-acc.js, packages/data-point-express/lib/inspector-middleware.js, packages/data-point-express/lib/route-middleware.js, packages/data-point-service/lib/entity-cache-params.js, packages/data-point-service/lib/factory.test.js, packages/data-point-service/lib/setup-middleware.js, packages/data-point/examples/middleware-exit-chain.js, packages/data-point/lib/entity-types/entity-request/resolve.js, packages/data-point/lib/entity-types/entity-request/resolve.test.js, packages/data-point/lib/reducer-types/reducer-entity-id/factory.js, packages/data-point/lib/reducer-types/reducer-object/factory.js, packages/data-point/lib/utils/index.js, packages/data-point/package.json, yarn.lock
**What**:
fixes #348
**Why**:
Address vulnerability alerts
**How**:
Upgrades devDependencies
**Checklist**:
=> build: upgrade devDependencies

packages/data-point/src/Accumulator.js, packages/data-point/src/Accumulator.test.js, packages/data-point/src/data-point.js
**What**:
Add tests for Accumulator module
**Why**:
there is none
**Checklist**:
=> test(data-point): add tests for Accumulator module

packages/data-point/src/Accumulator.js, packages/data-point/src/Accumulator.test.js, packages/data-point/src/Reducer.js, packages/data-point/src/Reducer.test.js, packages/data-point/src/ReducerEntity.js, packages/data-point/src/ReducerEntity.test.js, packages/data-point/src/data-point.js, packages/data-point/src/resolve-reducer.js, packages/data-point/src/resolve.js, packages/data-point/src/resolve.test.js, packages/data-point/src/trace-span.js, packages/data-point/src/trace-span.test.js, packages/data-point/src/unique-id-scope.js, packages/data-point/src/unique-id-scope.test.js
**What**:
adds tests and applies internal refactors to codebase
**Why**:
missing unit test:  re #357
**Checklist**:
=> Add tests reducers

packages/data-point/src/ReducerList.js, packages/data-point/src/ReducerList.test.js
**What**:
Adds tests to ReducerList Module
re  #357
**Checklist**:
=> refactor(data-point): add ReducerList tests

packages/data-point/src/Reducer.js, packages/data-point/src/Reducer.test.js, packages/data-point/src/is-reducer-constant.js, packages/data-point/src/is-reducer-constant.test.js, packages/data-point/src/reducer-helpers/constant/constant.js, packages/data-point/src/reducer-helpers/constant/constant.test.js, packages/data-point/src/reducer-helpers/constant/index.js
**What**:
Adds ReducerConstant, its a dependency for porting the ReducerObject
**Checklist**:
=> feat(data-point): add ReducerConstnat support

packages/data-point/src/ReducerObject.js, packages/data-point/src/ReducerObject.test.js, packages/data-point/src/is-plain-object.js, packages/data-point/src/is-plain-object.test.js, packages/data-point/src/reducer-helpers/constant/constant.js, packages/data-point/src/reducer-helpers/constant/constant.test.js
**What**:
closes #386 
**Why**:
As per discusses in https://github.com/ViacomInc/data-point/pull/383#discussion_r316423143
**Checklist**:
=>  constant check object

packages/data-point/src/create-reducer.js, packages/data-point/src/create-reducer.test.js
**What**:
closes #394
**Checklist**:
=> test(data-point): add tests for create-reducer

docs/playground-entity.js, docs/playground.js, packages/data-point/src/ReducerEntity.js, packages/data-point/src/ReducerEntity.test.js
**What**:
Changes cache api: 
- `get(acc)` to `get(uid, acc)`
- `set(acc)` to `set(uid, acc)`
**Why**:
this change moves away from attaching the uid to the accumulator which would cause confusion on the relationship of the `accumulator` and the `uid` property 
**Checklist**:
=> Refactor cache api

packages/data-point/src/Accumulator.js, packages/data-point/src/Reducer.js, packages/data-point/src/ReducerObject.js, packages/data-point/src/ReducerPath.js, packages/data-point/src/create-reducer.js, packages/data-point/src/is-plain-object.js, packages/data-point/src/reducer-helpers/constant/constant.js, packages/data-point/src/reducer-helpers/if-then-else/if-then-else.js, packages/data-point/src/reducer-helpers/map/map.js, packages/data-point/src/reducer-helpers/select/select.js, packages/data-point/src/resolve.js, packages/data-point/src/trace-span.js
**What**:
Ongoing changes to meet #360 
**Checklist**:
=> docs(data-point): adds JSDoc across files

package.json, yarn.lock
**What**:
Updates jest version and adds jest types for autocomplete in vscode (or supported editors)
**Checklist**:
=> build: update jest version and add jest types

.travis.yml
**What**:
removes prettier standard check, we are using airbnb now, more commits to come
**Checklist**:
=> ci: remove prettier-standard check

packages/data-point/src/ReducerEntity.js, packages/data-point/src/ReducerEntity.test.js
**What**:
closes #423 
**Checklist**:
=> fix entity not passing error

.npmpackagejsonlintrc.json, documentation/examples/mermaid-graph/package.json, documentation/examples/opentracing/package.json, documentation/website/package.json, package.json, packages/bench-trial/package.json, packages/data-point-cache/package.json, packages/data-point-express/package.json, packages/data-point-service/package.json, packages/data-point-tracers/LICENSE, packages/data-point-tracers/README.md, packages/data-point-tracers/package.json, packages/data-point/package.json, yarn.lock
**What**:
adds linter to check all package.json files are correctly structured
**Why**:
Many of the package.json files were missing important metadata.
**How**:
- updated files
- added a new linter to make sure files are well kept going forward
**Checklist**:
=> chore: update all package.json files

package.json, yarn.lock
**What**:
Adds types for testing
**Why**:
So we can get jest's type hints when writing tests.
**How**:
adding [@types/jest](https://www.npmjs.com/package/@types/jest)
**Checklist**:
=> test: adds types for testing

packages/data-point-service/lib/cache-middleware.js, packages/data-point-service/lib/cache-middleware.test.js
**What**:
closes #437
**Checklist**:
=> fix(data-point-service): pass value to addEntry when revalidating

packages/data-point-cache/lib/cache.js, packages/data-point-cache/lib/cache.test.js, packages/data-point-cache/lib/io-redis.js, packages/data-point-cache/lib/redis-client.js
**What**:
This PR only affects the `data-point-cache` package
re #434
**Checklist**:
=> feat(data-point-cache): migrate to async/await

packages/data-point/examples/reducer-entity-instance.js
**What**:
Adds nock mocks for example
**Checklist**:
=> docs(data-point): fix example not using mocks

CONTRIBUTING.md, jsconfig.json, packages/data-point-cache/package.json, packages/data-point-express/package.json, packages/data-point-service/lib/cache-middleware.test.js, packages/data-point-service/package.json, yarn.lock
**What**:
- Removes bluebird dependencies from packages I forgot to remove on previous PRs.
- Updates readme to reflect the change in async code style.
closes #434
**Checklist**:
=> build: remove bluebird dependency and update docs

.github/workflows/ci-actions.yml
**What**:
change job name to `integration-check`
**Why**:
job name was not meaningful
**Checklist**:
=> ci(github actions): change job to meaningful name
