- README.md
Fixed all occurances of 'transform('entry:getNodeOrgInfo', {' to
'dataPoint.transform('request:getNodeOrgInfo', {' in the README
Fix request string template example #7
> docs: Fix errors in the documentation for Request String Template

- packages/data-point/README.md
- packages/data-point/examples/custom-entity-type.js
Closes #11
This is a small change to the custom entity type example and a small change to the `data-point` README to be consistent.
To test the example run `node packages/data-point/examples/custom-entity-type.js` in the terminal.
> Fix custom entity type example

- packages/data-point/README.md
- packages/data-point/examples/custom-entity-type.js
- packages/data-point/lib/core/normalize-entities.js
- packages/data-point/lib/entity-types/entity-collection/factory.js
- packages/data-point/lib/entity-types/entity-control/factory.js
- packages/data-point/lib/entity-types/entity-entry/factory.js
- packages/data-point/lib/entity-types/entity-hash/factory.js
- packages/data-point/lib/entity-types/entity-request/factory.js
- packages/data-point/lib/entity-types/entity-schema/factory.js
- packages/data-point/lib/entity-types/entity-transform/factory.js
- packages/data-point/lib/helpers/helpers.js
- packages/data-point/lib/helpers/helpers.test.js
- packages/data-point/lib/stores/store-manager.js
transform entity should only accept a TransformExpression as its value
closes #51
**What**: fixes #51
**Why**:  current behavior is not as described in the documentation
**How**: 
1. not casting to object if value is not an object under core/factory.js
https://github.com/ViacomInc/data-point/blob/3e3da6ad20e2f6c1740e55a7f313cffc6b3be565/packages/data-point/lib/core/normalize-entities.js#L56-L60
2. entity extension only applied to entities that require it
https://github.com/ViacomInc/data-point/blob/3e3da6ad20e2f6c1740e55a7f313cffc6b3be565/packages/data-point/lib/core/normalize-entities.js#L39-L42
**Checklist**:
> fix(data-point/entities): normalize transform entity

- packages/data-point/lib/core/factory.js
**What**: Replace "entryPoints" property with "entityTypes" when adding default options.
**Why**: entryPoints is never used.
**Checklist**:
> Add default options.entityTypes object

- packages/data-point/lib/entity-types/entity-collection/factory.js
- packages/data-point/lib/entity-types/entity-hash/factory.js
- packages/data-point/lib/entity-types/parse-compose/parse-compose.js
- packages/data-point/lib/entity-types/parse-compose/parse-compose.test.js
**What**: Moved the `validateComposeVsInlineModifiers` function to `parse-compose.js` because it was defined twice (once for Hash entities and once for Collection entities). Also moved `validateCompose` and began using that for Collections (before it was only used by Hashes).
**Why**: DRY
**Checklist**:
> Move shared code to parse-compose.js

- packages/data-point/lib/entity-types/base-entity/factory.js
- packages/data-point/lib/entity-types/base-entity/resolve.js
- packages/data-point/lib/entity-types/entity-collection/factory.test.js
- packages/data-point/lib/entity-types/entity-control/factory.test.js
- packages/data-point/lib/entity-types/entity-entry/factory.test.js
- packages/data-point/lib/entity-types/entity-hash/factory.test.js
- packages/data-point/lib/entity-types/entity-request/factory.test.js
- packages/data-point/lib/entity-types/entity-schema/factory.test.js
- packages/data-point/lib/transform-expression/resolve.js
**What**: This will introduce a change that omits the lifecycle reducers from entities if they're not defined in the spec during their creation.
**Why**: This reduces the noise when debugging entities by removing unused keys. It could also improve the memory use by reducing the size of the objects being created.
**How**: Modifications to the `base-entity/factory#create` that checks for the existence of the `spec.before`/`spec.after`/`spec.error`.
**Checklist**:
- [N/A] Documentation
- [N/A] Added username to **all-contributors** list
> Remove empty lifecycle transforms

- packages/data-point/lib/entity-types/base-entity/resolve.test.js
- packages/data-point/lib/reducer-types/factory.js
- packages/data-point/lib/reducer-types/reducer-entity/factory.js
- packages/data-point/lib/reducer-types/reducer-entity/factory.test.js
- packages/data-point/lib/reducer-types/reducer-function/factory.js
- packages/data-point/lib/reducer-types/reducer-function/factory.test.js
- packages/data-point/lib/reducer-types/reducer-path/factory.js
- packages/data-point/lib/reducer-types/reducer-path/factory.test.js
- packages/data-point/lib/reducer-types/reducer-path/resolve.test.js
**What**: The reducer factories all take (createReducer, source) as parameters now.
**Why**: Consistency, which makes it easier to add new reducer types.
**Checklist**:
> Normalize reducer factory function signatures

- packages/data-point-service/lib/data-point-factory.test.js
- packages/data-point-service/lib/factory.test.js
- packages/data-point/README.md
- packages/data-point/examples/entity-entry-before.js
- packages/data-point/lib/entity-types/base-entity/factory.test.js
- packages/data-point/lib/reducer-types/reducer-function/factory.js
- packages/data-point/lib/reducer-types/reducer-path/factory.js
- packages/data-point/lib/reducer-types/reducer-path/factory.test.js
- packages/data-point/lib/reducer-types/reducer-path/resolve.test.js
- packages/data-point/test/definitions/hash.js
- packages/data-point/test/definitions/integrations.js
**What**: #52
**Why**: `$` can be used instead of `$.`
**Checklist**:
> feat(data-point/reducer-path): Deprecate the $. syntax for path reducers

- packages/data-point/README.md
- packages/data-point/lib/entity-types/entity-schema/__snapshots__/factory.test.js.snap
- packages/data-point/lib/entity-types/entity-schema/factory.js
- packages/data-point/lib/entity-types/entity-schema/factory.test.js
**What**: Closes #75
**Why**: Validates schemas that are passed to `EntitySchema#factory`, so we do not get schema validation errors at runtime.
**How**: Using `ajv.validateSchema`.
**Checklist**:
> feat(data-point/entity-schema): Throw errors for invalid schemas

- packages/data-point/lib/reducer-types/reducer-object/resolve.js
**What**: Use `Array.reduce` inside of `ReducerObject#resolve` (closes #164)
**Why**: Should improve performance.
**Checklist**:
> refactor(data-point/reducer-object): Replace a Promise.reduce with Array.reduce

- packages/data-point/lib/entity-types/entity-request/__snapshots__/resolve.test.js.snap
- packages/data-point/lib/entity-types/entity-request/resolve.js
- packages/data-point/lib/entity-types/entity-request/resolve.test.js
- packages/data-point/test/definitions/requests.js
**What**: Remove `auth` object from `request.options` before returning the `acc` or `error`, or printing those values to the console.
**Why**: The `options` object was being printed to the `console` with the authorization credentials. Depending on the implementation credentials could leak into stored logs and test snapshots without a user knowing. This removes authorization creds before returning the `acc`/`error`. ☠️ 
**How**: using [lodash/fp#set](https://github.com/lodash/lodash/wiki/FP-Guide)
**Checklist**:
> Omit options.auth from acc and error objects

- packages/data-point/lib/reducer-types/reducer-path/factory.js
- packages/data-point/lib/reducer-types/reducer-path/factory.test.js
**What**: closes #182, and slightly refactors the code for setting `ReducerPath` object properties.
**Why**: Looks better when logging reducers to the console, and makes it more obvious what the `ReducerPath#body` function is doing.
**How**: `Object.defineProperty`
**Checklist**:
> feat(data-point/reducer-path): Add a custom name to ReducerPath#body functions

- packages/data-point/README.md
- packages/data-point/lib/__snapshots__/index.test.js.snap
- packages/data-point/lib/helpers/__snapshots__/helpers.test.js.snap
- packages/data-point/lib/helpers/helpers.js
- packages/data-point/lib/reducer-types/factory.js
- packages/data-point/lib/reducer-types/reducer-helpers/index.js
- packages/data-point/lib/reducer-types/reducer-helpers/reducer-default/factory.js
- packages/data-point/lib/reducer-types/reducer-helpers/reducer-default/factory.test.js
- packages/data-point/lib/reducer-types/reducer-helpers/reducer-default/index.js
- packages/data-point/lib/reducer-types/reducer-helpers/reducer-default/resolve.js
- packages/data-point/lib/reducer-types/reducer-helpers/reducer-default/resolve.test.js
- packages/data-point/lib/reducer-types/reducer-symbol.js
- packages/data-point/lib/reducer-types/reducer-symbols.js
- packages/data-point/lib/reducer-types/resolve.js
- packages/data-point/lib/reducer-types/resolve.test.js
**What**: Adds the `ReducerDefault` type (closes #169)
**Why**: This will add default values to any reducer.
**How**: Instead of actually creating a new reducer type, this just adds a `default` property to any existing reducer. The property uses a symbol to avoid any future conflicts.
**Checklist**:
> feat(data-point/reducer-default: Add the ReducerDefault type

- packages/data-point/examples/entity-model-error-handled.js
- packages/data-point/lib/entity-types/base-entity/__snapshots__/resolve.test.js.snap
- packages/data-point/lib/entity-types/base-entity/resolve.js
- packages/data-point/lib/entity-types/base-entity/resolve.test.js
- packages/data-point/test/definitions/model.js
**What**: Moves the `inputType` and `outputType` resolution to the beginning/end of the entity resolution.
**Why**: Closes #202
**How**: just moved the lines really.
**Checklist**:
> Change execution order to have type checks as bookends

- packages/data-point/lib/entity-types/entity-request/resolve.test.js
**What**: Mock `console.info` so that the "helpful" information is hidden in the test output
**Why**: When entitiy-requests encounter an error we log info to the console and it looks ugly in the test output
**How**: `jest.fn()`
**Checklist**:
Perhaps we should remove/gate the `console.info` in the source, but until we do this is really annoying. Keep in mind that even though we mocked out `console.info`, our users will still see this message in their test output if they are testing for requests encountering an error. We've mocked all the logging out of the tests, it seems silly to leave it for users to be annoyed.
> Mock console.info from request entity being forced to err

- packages/data-point/lib/entity-types/base-entity/resolve.test.js
- packages/data-point/test/definitions/model.js
**What**: Test that middleware + entity lifecycle methods are executed in the correct order.
**Why**: I don't think this is being tested now.
**How**: Uses `acc.locals` to pass in lifecycle methods that use the same scope as the middleware that's being used.
> test(data-point/base-entity): Test that entity methods are executed in order

- packages/data-point/lib/__snapshots__/index.test.js.snap
- packages/data-point/lib/core/transform.js
- packages/data-point/lib/core/transform.test.js
- packages/data-point/lib/index.js
- packages/data-point/lib/reducer-types/factory.js
- packages/data-point/lib/reducer-types/factory.test.js
also allow existing reducers to be passed to resolve and transform functions
**What**: closes #233
**How**: Exports `createReducer` function and refactors `reducerResolve` 
**Checklist**:
> feat(data-point): Expose createReducer on DataPoint object

- packages/data-point/lib/entity-types/base-entity/resolve.js
- packages/data-point/lib/entity-types/base-entity/resolve.test.js
- packages/data-point/lib/middleware-control/middleware.js
- packages/data-point/lib/middleware/resolve.js
**What**: Refactors the base-entity resolve function.
**Why**: Performance. I tested a simple entity with bench-trial, and the resolve time went from 19,530 ops/sec to 25,353 ops/sec, which is a ~30% improvement.
```js
'model:test': {
value: () => true,
outputType: 'boolean'
}
```
**How**:
Added conditionals in `base-entity/resolve.js` to make sure lifecycle methods / middleware are defined before trying to execute them (which extends the promise chain).
**Checklist**:
> refactor(data-point): Do not try to execute undefined entity lifecycle methods

- packages/data-point-service/README.md
- packages/data-point-service/lib/__snapshots__/factory.test.js.snap
- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
- packages/data-point-service/lib/factory.js
- packages/data-point-service/lib/factory.test.js
use cache.redis.keyPrefix instead
BREAKING CHANGE: cache.prefix is no longer used, if set; an error is thrown to alert the user of the
change
**What**:
deprecated `cache.prefix` in favor or `cache.redis.keyPrefix`
**Why**:
There were two places where this was possible to be set, and the cache.prefix was not the right approach, prefixing should be delegated to native ioredis options.
**How**:
Removed the feature, added a check if the value is set, then throw an error to alert the user of the change.
**Checklist**:
> feat(data-point-service): deprecates cache.prefix

- packages/data-point-service/README.md
- packages/data-point-service/examples/express-cache-stale-while-revalidate.js
- packages/data-point-service/examples/express-simple-cache.js
- packages/data-point-service/lib/__snapshots__/cache-middleware.test.js.snap
- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
**What**:
#275
**How**:
Attempting to correctly implement the RFC https://tools.ietf.org/html/rfc5861#section-3
Enables staleWhileRevalidate to be `string` (ms) or `number`, it is now calculated as an addition to the given **ttl**.
to give backward compatibility with `boolean`, when set as `true` it will resolve to a **ttl** of twice as the given `cache.ttl`
**Checklist**:
> Fix stale while revalidate stale ttl logic

- packages/data-point-service/lib/__snapshots__/cache-middleware.test.js.snap
- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
it now checks for revalidation cache key vs current cache key to prevent multiple revalidations
**What**:
im sorry :) two bugs included in one single PR
- fixes revalidation logic
- changes key generation prefix to postfix
**Why**:
- revalidation logic was not checking against being the same cache key, so it would essentially re-revalidate every single entity
- stale-while-revalidate key prefixes were not helping with the taxonomy of the key
**How**:
- we check against the cache key being revalidated and the current one, only if it matches
- moving the stale-while-revalidate key from prefix to postfix allows us to filter by anything preceding it
**Checklist**:
> fix(data-point-service): fix revalidation logic and key creation

- packages/data-point/lib/entity-types/entity-request/resolve.js
- packages/data-point/lib/entity-types/entity-request/resolve.test.js
- packages/data-point/lib/utils/index.js
- packages/data-point/lib/utils/utils.test.js
inspect was adding extra logging, this offloads the entire behaviour to the custom function
closes #263
**What**:
fixes #263 
**How**:
offloading any inspect functionality to the custom inspect function
**Checklist**:
> fix(data-point): fix request.params.inspect

- packages/data-point-service/README.md
- packages/data-point-service/lib/__snapshots__/cache-middleware.test.js.snap
- packages/data-point-service/lib/__snapshots__/revalidation-store.test.js.snap
- packages/data-point-service/lib/__snapshots__/stale-while-revalidate.test.js.snap
- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
- packages/data-point-service/lib/entity-cache-params.js
- packages/data-point-service/lib/entity-cache-params.test.js
- packages/data-point-service/lib/no-entry-found.js
- packages/data-point-service/lib/redis-controller.js
- packages/data-point-service/lib/redis-controller.test.js
- packages/data-point-service/lib/revalidation-store.js
- packages/data-point-service/lib/revalidation-store.test.js
- packages/data-point-service/lib/stale-while-revalidate.js
- packages/data-point-service/lib/stale-while-revalidate.test.js
closes #303
**What**:  prevents duplicate revalidations from happening when concurrent calls happen to access the same key
**Why**: when concurrent calls are made, duplicate revalidations may trigger causing reace-condition and waste of resources
**How**: adding a local and remote (redis) flags to tell the system when a key is being revalidated and prevent new revalidations to happen while a current revalidation is in place
Adds a new parameter called `revalidationTimeout` explained on the README changes.
**Checklist**:
> feat(data-point-service): support revalidation concurrency

- packages/data-point/README.md
- packages/data-point/lib/entity-types/entity-request/__snapshots__/resolve.test.js.snap
- packages/data-point/lib/entity-types/entity-request/resolve.js
- packages/data-point/lib/entity-types/entity-request/resolve.test.js
**What**: fix #324
**Why**: This adds more functionality to the `inspect` function for request entities. The function now has two parameters: `accumulator` and `data`, where the data object contains information like the fully-formed URI and the response status code. This replaces #328, which introduced the `request-debug` library as a dependency.
**Checklist**:
> feat(data-point): Add more functionality to the inspect function for request entities

- packages/data-point/lib/entity-types/entity-request/resolve.js
- packages/data-point/lib/entity-types/entity-request/resolve.test.js
**What**: Use `lodash.attempt` when calling `inspect` functions
**Why**: Helps prevent user errors from crashing data-point
**Checklist**:
> feat(data-point): Use _.attempt when calling user defined inspect functions

- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
- packages/data-point/README.md
- packages/data-point/examples/middleware-exit-chain.js
- packages/data-point/lib/entity-types/base-entity/resolve.test.js
- packages/data-point/lib/middleware-context/factory.js
- packages/data-point/lib/middleware-context/factory.test.js
- packages/data-point/lib/middleware-control/middleware.js
- packages/data-point/lib/middleware-control/middleware.test.js
**What**:
Refactors the middleware API to now use the `next()` method to exit/resolve the middleware(stack) chain. 
**Why**:
#206 
**How**:
Changing data-point and updating data-point-service to use the new API
**Checklist**:
**ADDS BREAKING CHANGE:**
API changed, middleware acc.resolve is no longer available it will be repurposed
later on. To achieve the previous functionality you must pass a second parameter to the `next()` method.
See README for new API and examples on how to use it.
> 206 use next instead of resolve

- packages/data-point-service/examples/express-cache-stale-while-revalidate-instance-entity.js
- packages/data-point-service/examples/express-cache-stale-while-revalidate-registered-entity.js
- packages/data-point-service/lib/__snapshots__/cache-middleware.test.js.snap
- packages/data-point-service/lib/__snapshots__/data-point-factory.test.js.snap
- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
- packages/data-point-service/lib/data-point-factory.js
- packages/data-point-service/lib/data-point-factory.test.js
- packages/data-point-service/lib/stale-while-revalidate.js
- packages/data-point-service/lib/stale-while-revalidate.test.js
**What**:
- fix bug where revalidation was not being triggered
- provides support registered and instance entities
**Why**:
closes #340
**How**:
passing the entity reducer (accumulator.context) to resolveFromAccumulator, and fixed logic to detect when a remote (redis) entry should revalidate.
I also added more debugging logs since it was getting harder to track the steps, this should help in the future, below is an example of the output of running one of the examples: 
```bash
data-point:entity:model model:HelloWorld:1 - resolve:start +0ms
data-point-service:cache:stale-while-revalidate External control exists: false - entity:model:HelloWorld +0ms
data-point:entity:model model:HelloWorld:1 - resolve +30ms
data-point-service:cache:stale-while-revalidate Adding entry - …
```
> fix(data-point-service): fixes revalidation logic

- package.json
- packages/data-point/package.json
- yarn.lock
**What**:
closes #342
**Why**:
closes #342
**How**:
Removed commitizen legacy dependencies and scripts, set a fix dependency version on root package.json
the output now is: 
```bash
$ yarn install
yarn install v1.15.2
$ scripts/preinstall-script.js
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > data-point-express@4.1.4-0" has unmet peer dependency "express@4.x".
[4/4] 🔨  Building fresh packages...
✨  Done in 14.08s.
```
**Checklist**:
> build(root, data-point): yarn warning cz-conventional-changelog

- packages/data-point/lib/reducer-types/reducer-list/resolve.js
- packages/data-point/lib/reducer-types/reducer-list/resolve.test.js
**What (Bugfix)**: Reducer lists currently skip the first reducer when the initial value is undefined
**Why**: #353
**How**: Use null as a fallback when the initial value for Promise.map is undefined
**Checklist**:
> fix: Fix bug when the input to a reducer list is undefined

- packages/data-point/src/ReducerEntity.js
- packages/data-point/src/ReducerEntity.test.js
**What**:
Makes sure any error is re-thrown if not handled by the catch reducer
**Why**:
ReducerEntity was not throwing error
**Checklist**:
> fix(data-point): ReducerEntity is now rethrowing error when not handled

- documentation/examples/mermaid-graph/mermaid-example.js
- documentation/examples/mermaid-graph/package.json
- packages/data-point-tracers/mermaid/index.js
- packages/data-point-tracers/mermaid/mermaid.js
- packages/data-point-tracers/mermaid/mermaid.test.js
**What**:
closes #419
**Checklist**:
> feat(data-point-tracers): add mermaid support

- packages/data-point-service/README.md
- packages/data-point-service/examples/express-cache-schema-revalidation.js
- packages/data-point-service/lib/cache-middleware.js
- packages/data-point-service/lib/cache-middleware.test.js
- packages/data-point-service/package.json
- yarn.lock
**What**:
fixes #451
if `outputType` reducer is set, it must pass in order for the entry to be added to the cache store.
**Why**:
See #451
**How**:
By running executing outputType reducer before adding the entry into the cache store.
**Checklist**:
> feat(data-point-service): run outputType before adding entry

- .github/workflows/ci-actions.yml
**What**: Temporarily disabled codecov
**Why**: It is blocking the main pipeline
**How**: Just commented the gh ci workflow
**Checklist**:
> ci(codecov): temporary disabled codecov from CI process
